### ISSUE TITLE
support TF>=2.7 to support Py>=3.10

### ISSUE THREAD

**Issue by bertsky** [Planet-AI-GmbH/tf2_aip_base#11]
> Can't install Calamari 2.2.2 on Python 3.10: It depends on `tfaip==1.2.6` which in return depends on `tensorflow<2.7.0,>=2.4.0`, but PyPi only has 2.8.0+ available for Python 3.10.

_Originally posted by @mikegerber in https://github.com/Calamari-OCR/calamari/issues/304#issuecomment-1192723665_

**Comment by ocrwork** [comment]
I have been working on getting tfaip working with python 3.10 and tf 2.11
So far, I have 11 failed, 42 passed out of 53 unit tests.
test_tutorial_full, test_experimenter 1 of 3, test_lav, test_accum_optimizer,  fail
Can someone assist me with this project? I have not found a debug tool that I can use to debug tfaip.
Also, I don't understand how to best address some of the error messages.

**Comment by TobiasGruening** [comment]
Since the hopes we had for the release of the repo have not been fulfilled, we will freeze it at its current state, archive it and no longer maintain it in the open source variant.

I'm sorry if this leads to problems, but we have to direct our resources a little differently.
